### ISSUE TITLE
Older vsts-python-api packages have unconstrained upper dependency on msrest

### ISSUE THREAD

**Issue by akrherz** [conda-forge/vsts-python-api-feedstock#11]
### Comment:

With the new mamba dep solver, I am seeing very aggressive attempts to install older packages with unconstrained dependencies.  In this case, it is finding older [vsts-python-api releases](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Fvsts-python-api-0.1.22-py_0.tar.bz2) with a dep of `msrest >=0.5.0`.  I'll PR a metadata patch to constrain these to <0.6

**Comment by ocefpaf** [comment]
While we should update these packages metadata, it is odd that this regression is showing up.

**Comment by akrherz** [comment]
Thanks for the repodata patch merge, I am not reproducing the issue locally anymore.
